
services:
  web:
    build: .
    # env_file: ./.env
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    networks:
      - app-network

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - app-network
  pgadmin:
    container_name: symfony-taxi_pgadmin
    image: dpage/pgadmin4:7.2
    env_file:
      - ./.env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8081:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - database
    networks:
      - app-network

  graphhopper:
    ports:
      - 8989:8989
    image: israelhikingmap/graphhopper
    command: --url https://download.openstreetmap.fr/extracts/russia/central_federal_district/lipetsk_oblast-latest.osm.pbf --host 0.0.0.0
    restart: unless-stopped
    volumes:
      - graphhopper_data:/data

volumes:
  database_data:
  pgadmin:
  graphhopper_data:


networks:
  app-network:
    driver: bridge