controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# catch_all:
#     path: /{path}
#     controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
#     defaults:
#         route: app_main  # Your main route name
#         permanent: true
#     requirements:
#         path: ".*"